# Generated by Django 6.0.1 on 2026-02-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_throttled'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_tenant__b114ab_idx',
            old_name='jobs_job_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_created_1b3a4d_idx',
            old_name='jobs_job_created_at_idx',
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('THROTTLED', 'Throttled'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('DLQ', 'Dead Letter Queue')], default='PENDING', max_length=20),
        ),
    ]
