# Generated by Django 6.0.1 on 2026-02-01 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_rename_jobs_job_tenant_status_idx_jobs_job_tenant__b114ab_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['tenant', 'idempotency_key'], name='jobs_job_tenant__5f331d_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('tenant', 'idempotency_key'), name='unique_tenant_idempotency_key'),
        ),
    ]
